title:            Serge Ballif
description:      "pi is exactly 3"
logo:             logo.png
# disqus_shortname: hmfaysal
share:        	true
dropcap:	true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same 
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:  http://sergeballif.github.io

# Owner/author information
owner:            
  name:           Serge Ballif
  avatar:         JekyllAndHyde.png
  email:          serge.ballif@nsc.edu
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    I'm a math professor at Nevada State College with a strong desire to be a great teacher. 
  # Social networking links used in footer. Update and remove as you like.
  twitter:        https://twitter.com/sergeballif
  #facebook:       
  github:         https://github.com/sergeballif     
  #instagram:      
  # For Google Authorship https://plus.google.com/authorship
  # google_plus:   

# Analytics and webmaster tools stuff goes here
# google_analytics:   UA-39365944-7
# google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Featured Posts
    url: /featured
  - title: Categories
    url: /categories
  - title: About
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
gems: [jekyll-paginate]
timezone:    America/Los_Angeles
future:      true
highlighter: rouge
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

prose:
  rooturl: '_posts'
  siteurl: 'http://sergeballif.github.io/' #'http://hmfaysal.github.io/Notepad/'
  relativeLinks: 'http://sergeballif.github.io/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "false"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "headline"
        field:
          element: "text"
          label: "headline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "Math"
              value: math
            - name: "Teaching"
              value: teaching
            - name: "Fun"
              value: fun
            - name: "Writing"
              value: writing
            - name: "Interesting"
              value: interesting
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: true
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false


include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
